---
dbt_ai:
  target: dev
  outputs:
    ci:
      dataset: "{{ env_var('DBT_DATASET', 'ci') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{ env_var('GCP_PROJECT', 'dbt-ai-demo') }}"
      threads: 16
      type: bigquery
    dev:
      dataset: "{{ env_var('DBT_DATASET', 'dev') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{ env_var('GCP_PROJECT', 'dbt-ai-demo') }}"
      threads: 16
      type: bigquery
    prod:
      dataset: dbt_ai_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{ env_var('GCP_PROJECT', 'dbt-ai-demo') }}"
      threads: 16
      type: bigquery
